{"uuid": "e7ddaad5-45f5-4a04-8ab6-c21126e3402d", "children": ["ddf90f55-a0d2-481a-9fee-ae97606fc952"], "befores": [{"name": "get_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: failed to change window state to 'normal', current state is 'maximized'\n  (Session info: chrome=108.0.5359.125)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0113F243]\n\t(No symbol) [0x010C7FD1]\n\t(No symbol) [0x00FBD04D]\n\t(No symbol) [0x00FA6631]\n\t(No symbol) [0x00FA5470]\n\t(No symbol) [0x00FA4369]\n\t(No symbol) [0x0102C7CF]\n\t(No symbol) [0x0100858C]\n\t(No symbol) [0x0101C9EB]\n\t(No symbol) [0x01008386]\n\t(No symbol) [0x00FE163C]\n\t(No symbol) [0x00FE269D]\n\tGetHandleVerifier [0x013D9A22+2655074]\n\tGetHandleVerifier [0x013CCA24+2601828]\n\tGetHandleVerifier [0x011E8C0A+619850]\n\tGetHandleVerifier [0x011E7830+614768]\n\t(No symbol) [0x010D05FC]\n\t(No symbol) [0x010D5968]\n\t(No symbol) [0x010D5A55]\n\t(No symbol) [0x010E051B]\n\tBaseThreadInitThunk [0x75DC6939+25]\n\tRtlGetFullPathName_UEx [0x77228FD2+1218]\n\tRtlGetFullPathName_UEx [0x77228F9D+1165]\n\n", "trace": "  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1128, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 900, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\pythonPOMProject\\Testcases\\conftest.py\", line 21, in get_browser\n    driver.maximize_window()\n  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 607, in maximize_window\n    self.execute(command, None)\n  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\pythonpomproject\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1671560636146, "stop": 1671560662593}], "start": 1671560636146, "stop": 1671560662903}